server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: eb-nestjs
          __path__: /var/log/app/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            context: context
            requestId: requestId
            method: method
            url: url
            statusCode: statusCode
            duration: duration
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          context:
          requestId:
          method:
          statusCode:
